version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuPassword123*
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=sqlserver
      - DB_USER=sa
      - DB_PASS=TuPassword123*
      - DB_NAME=MiBase
      - DB_PORT=1433
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
